
# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="dota2theme.mp3"
Content-Type: audio/mpeg

< ./dota2theme.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create
POST http://localhost:3333/videos/2828c94f-af89-4121-9e46-f24c09ba9b08/transcription
Content-Type: application/json

{
    "prompt": "amor, helena"
}

###

# @name generate
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "2828c94f-af89-4121-9e46-f24c09ba9b08",
    "temperature": 0.5,
    "prompt": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}

